USE [master]
GO

/****** Object:  Database [IMData]    Script Date: 01/14/2018 19:27:41 ******/
CREATE DATABASE [IMData] ON  PRIMARY 
( NAME = N'IMData', FILENAME = N'G:\数据库\IMData.mdf' , SIZE = 11264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IMData_log', FILENAME = N'G:\数据库\IMData_log.ldf' , SIZE = 43264KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IMData] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IMData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IMData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IMData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IMData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IMData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IMData] SET ARITHABORT OFF 
GO

ALTER DATABASE [IMData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IMData] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IMData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IMData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IMData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IMData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IMData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IMData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IMData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IMData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IMData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IMData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IMData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IMData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IMData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IMData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IMData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IMData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IMData] SET  READ_WRITE 
GO

ALTER DATABASE [IMData] SET RECOVERY FULL 
GO

ALTER DATABASE [IMData] SET  MULTI_USER 
GO

ALTER DATABASE [IMData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IMData] SET DB_CHAINING OFF 
GO


USE [IMData]
GO

/****** Object:  Table [dbo].[ErrorLogs]    Script Date: 01/14/2018 19:27:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ErrorLogs](
	[id] [int] NOT NULL,
	[UpdateUid] [nchar](8) NOT NULL,
	[MsgContent] [nchar](500) NOT NULL,
	[UpdateTime] [date] NOT NULL,
 CONSTRAINT [PK_ErrorLogs] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[Face]    Script Date: 01/14/2018 19:28:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Face](
	[FaceID] [int] IDENTITY(0,1) NOT NULL,
	[Face] [image] NOT NULL,
 CONSTRAINT [PK_Face] PRIMARY KEY CLUSTERED 
(
	[FaceID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[FriendRelation]    Script Date: 01/14/2018 19:28:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FriendRelation](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[SendUid] [nchar](8) NOT NULL,
	[AcceptUid] [nchar](8) NOT NULL,
	[AcceptTime] [date] NOT NULL,
 CONSTRAINT [PK_FriendRelation] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[FriendRequest]    Script Date: 01/14/2018 19:28:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FriendRequest](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[SendUid] [nchar](8) NOT NULL,
	[AcceptUid] [nchar](8) NOT NULL,
 CONSTRAINT [PK_UnHandlerFriendRequest] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[ImgMsg]    Script Date: 01/14/2018 19:28:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ImgMsg](
	[MsgId] [nchar](70) NOT NULL,
	[Msg] [image] NOT NULL,
 CONSTRAINT [PK_ImgMsg] PRIMARY KEY CLUSTERED 
(
	[MsgId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[Log]    Script Date: 01/14/2018 19:28:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Log](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Uid] [nchar](8) NOT NULL,
	[Msg] [nchar](300) NOT NULL,
	[Ip] [nchar](15) NOT NULL,
	[Time] [date] NOT NULL,
 CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[MessageInfo]    Script Date: 01/14/2018 19:28:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MessageInfo](
	[MsgId] [nchar](70) NOT NULL,
	[SendUid] [nchar](8) NOT NULL,
	[RecviceUid] [nchar](8) NOT NULL,
	[time] [datetime] NOT NULL,
	[MsgType] [int] NOT NULL,
	[ReceiverStatus] [bit] NOT NULL,
 CONSTRAINT [PK_MessageInfo] PRIMARY KEY CLUSTERED 
(
	[MsgId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[NotityInfo]    Script Date: 01/14/2018 19:29:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NotityInfo](
	[id] [int] NOT NULL,
	[Title] [nchar](30) NOT NULL,
	[Content] [nchar](1000) NOT NULL,
	[SendUid] [nchar](10) NOT NULL,
 CONSTRAINT [PK_NotityInfo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[OtherMsg]    Script Date: 01/14/2018 19:29:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OtherMsg](
	[MsgId] [nchar](70) NOT NULL,
	[Msg] [nchar](300) NULL,
 CONSTRAINT [PK_OutherMsg] PRIMARY KEY CLUSTERED 
(
	[MsgId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[SoundMsg]    Script Date: 01/14/2018 19:29:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SoundMsg](
	[MsgId] [nchar](70) NOT NULL,
	[Msg] [image] NOT NULL,
 CONSTRAINT [PK_SoundMsg] PRIMARY KEY CLUSTERED 
(
	[MsgId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[TxtMsg]    Script Date: 01/14/2018 19:29:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TxtMsg](
	[MsgId] [nchar](70) NOT NULL,
	[Msg] [nchar](1000) NOT NULL,
 CONSTRAINT [PK_MessageContent] PRIMARY KEY CLUSTERED 
(
	[MsgId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[UnHandlerEvent]    Script Date: 01/14/2018 19:29:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UnHandlerEvent](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Uid] [nchar](10) NOT NULL,
	[EventType] [int] NOT NULL,
 CONSTRAINT [PK_UnHandlerEvent] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [IMData]
GO

/****** Object:  Table [dbo].[UserInfo]    Script Date: 01/14/2018 19:29:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserInfo](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Uid] [nchar](8) NOT NULL,
	[Pwd] [nchar](18) NOT NULL,
	[Alias] [nchar](20) NOT NULL,
	[FaceID] [int] NULL,
	[RegTime] [date] NOT NULL,
	[Token] [nchar](70) NULL,
	[TokenGenerateTime] [date] NULL,
	[BirthDay] [date] NULL,
	[Sex] [bit] NULL,
 CONSTRAINT [PK_T_UserInfo] PRIMARY KEY CLUSTERED 
(
	[Uid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


